import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

import { Overpass } from "next/font/google";

const overpass = Overpass({ style: ["normal"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={overpass.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
